### PR TITLE
SMT2 translator

### PR DESCRIPTION
**Pull request by mrphrazer**
This PR introduces a translator for the SMT2 standard. With this, SMT formulas can be solved independently from Z3 by any SMT solver that supports the standard.

### CODE REVIEW

**Comment by serpilliere** [comment]
Hey, it seems Santa Claus did a great job during the holidays :smiley:

**Comment by mrphrazer** [comment]
Thanks :)

I ran a few more tests and fixed one bug in ExprId and refactored minor things.

**Comment by serpilliere** [comment]
Ok, just a little bug: @commial raised the fact that:
```python
testset += RegressionTest(["z3_ir.py", "smt2.py"], base_dir="ir/translators",
```

will not run the `smt2.py`: it will pass it as argument for `z3_ir.py`
(you can check this by insering a bad test, and test_all won't see it)

You need to inser an independant test line!

**Comment by mrphrazer** [comment]
thanks, you are right! fixed.

**Comment by serpilliere** [comment]
Perfect.

**Pull request merged**
