### PR TITLE
Various improvements towards x86 64-bit compatibility

### PR DESCRIPTION
**Pull request by rom1sqr**
The commit messages explain each change rather well.

### CODE REVIEW

**Comment by rom1sqr** [comment]
```
FAIL: test_ExprOp_toC (__main__.TestIrIr2C)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ir2C.py", line 24, in test_ExprOp_toC
    ExprOp('parity',  *args[:1]), r'parity(0x0&0xffffffff)')
  File "ir2C.py", line 13, in translationTest
    self.assertEqual(translator.from_expr(expr), expected)
AssertionError: 'parity(0x0ULL&0xffffffff)' != 'parity(0x0&0xffffffff)'
```

I let you choose how you want that solved :
- either you can remove this utterly useless string comparison ;
- either i adapt it to reflect the recent changes made in this PR.
Your move ! :)

**Comment by serpilliere** [comment]
I tend to select the option which removes the test!

**Comment by rom1sqr** [comment]
ok ! i'll modify the PR to reflect that choice asap.

**Comment by rom1sqr** [comment]
done !

**Comment by serpilliere** [comment]
Close (re submit)

**Pull request closed without merging**
