### PR TITLE
Add expr type access

### PR DESCRIPTION
**Pull request by serpilliere**
Replace `isintance(expr, ExprIn)` by `expr.is_int()`
Code cleanup

### CODE REVIEW

**Comment by commial** [comment]
OK, so Is the goal of this PR a better code readability? (Or am I missing something?)

Going this way, why not applying your change to every Miasm code? Such as in `asmbloc.py:expr_is_*` for instance.

Final point: if homogenization to this new API is decided, I'll prefer to wait current big PR to land to avoid useless conflict. What do you think?

**Comment by serpilliere** [comment]
The `expr.is_XXX` adds feature to `Expr` class **only**. The `expr_is*` if defined in `asmbloc`because this code uses class defined in this module.

The `asmbloc` module in miasm depends on `expression`, and the `expression` module does **not** rely on asmbloc (there is no cross references)

So for me, no, this code cannot be generalized for `expr_is*`. By the way, for my point of view, this is not really a code readability, it's more a convenience to write code :smile:

**Comment by commial** [comment]
Ok, this is not I wanted to say. My point is that you can apply this replacement in others miasm code parts, as in the body of expr_is_* function

**Comment by serpilliere** [comment]
Yes: If you don't have any arguments against the use of such a code, I may effectively replace other parts.

**Comment by serpilliere** [comment]
Note this can be done in future patch as well. There is no need to fix **every** code in the same code.

**Comment by commial** [comment]
Fair point. Work for me!

**Pull request merged**
