### PR TITLE
Fix build mac os x

### PR DESCRIPTION
**Pull request by alvarofe**
Was trying miasm on mac os x but I wasn't able to build it. That seems to fix the issue.

### CODE REVIEW

**Comment by commial** [comment]
This is actually the patch introduced in #27 . It seems OK for me to land it.
Did you get the emulation working?

**Comment by alvarofe** [comment]
Did you have a test for that to try it?

**Comment by commial** [comment]
Yes, you can launch Miasm regression tests and example through:
```
cd tests;
python test_all.py
```

**Comment by dnutiu** [comment]
Got the same error

**Pull request closed without merging**
