### PR TITLE
Clean encode's value check

### PR DESCRIPTION
**Pull request by 327135569**
Seems we can do it in one pleace in cpu.py. it simple than check value and mask in every encode() ?

### CODE REVIEW

**Comment by serpilliere** [comment]
Hi @327135569 
Yep, it seems to greatly simplify the code.
What makes me think twice what the fact that with this patch, the `self.value` is left 'unattended  until the return.
But yes, it seems ok after all.

**Comment by 327135569** [comment]
I am not very clear, is this mask check used to filter out mismatched mnemonics? If yes, I think it is necessary to do the check in each encode().  but now, not every encode() do this check.

**Comment by serpilliere** [comment]
Yes, it's there to check if the encoded value is correct. That's why your fix seems legit

**Comment by serpilliere** [comment]
Thank you for the PR @327135569 !

**Pull request merged**
