### PR TITLE
Ported IDAPython code to the 7.4 version

### PR DESCRIPTION
**Pull request by nofiv**
Solves #1183

### CODE REVIEW

**Comment by commial** [comment]
Hi,

Thanks for the PR. Quick test here (IDA 7.4, Linux, Python3):
* on `menu` import, I got:
```
WARNING: The method "ida_kernwin.UI_Hooks::finish_populating_tform_popup" won't be called (it has been replaced with "ida_kernwin.UI_Hooks::finish_populating_widget_popup")
```
* on graph IR, I got:
```
graph_ir.py", line 335, in function_graph_ir
    func_addr = func.startEA
...
AttributeError: Property startEA has been replaced with start_ea
```
* after fixing the one above, I got (probably not related to your PR):
```
IDAPython: Error while calling Python callback <OnRefresh>:
unhashable type: 'IRBlock'
  File "example/ida/graph_ir.py", line 130, in OnRefresh
    addr_id[irblock] = id_irblock
```

**Comment by nofiv** [comment]
Sorry @commial, I'm currently using mostly the dep graph and I apaprently forgot to test rest of the features. It works now with the fixes and @serpilliere 's PR

**Comment by commial** [comment]
Thanks, LGTM once rebase on #1189

**Comment by serpilliere** [comment]
So @nofiv : are you ok if I merge #1189, and you rebase yours after this one ?

**Comment by nofiv** [comment]
Yes @serpilliere

**Comment by serpilliere** [comment]
I just merged the #1189

**Comment by nofiv** [comment]
I just rebased it @serpilliere

**Comment by serpilliere** [comment]
Thank you @nofiv 
I will wait a bit to let people upgrade to IDA 7.4 and merge it.

**Comment by XVilka** [comment]
I think everyone who could have upgraded already did.

**Comment by serpilliere** [comment]
Sorry, but I didn't get my license upgrade yet :smile:

**Comment by serpilliere** [comment]
@a-vincent  just hint me that it was compatible with my current ida version.
I have successfully tested it
Sorry for this!

**Comment by serpilliere** [comment]
Thank you for the PR @nofiv !

**Pull request merged**
