### PR TITLE
Fix build on macOS with latest XCode

### PR DESCRIPTION
**Pull request by trufae**

### CODE REVIEW

**Comment by trufae** [comment]
(didn't tried on previous versions)

**Comment by serpilliere** [comment]
Hi @trufae !
Can you confirm that with this patch, Miasm builds on Mac ?

**Comment by trufae** [comment]
Yep. Thats why i have submitted it :)

**Comment by serpilliere** [comment]
A little question:
why do you swap the `__BYTE_ORDER` definition in windows environement?

**Comment by trufae** [comment]
Just to be consistent in the way we define things on all the systems. Otherwise it hurts my eyes. Keep them in the same order. We can switch to alphabetical order too, but all those 3 defines should be happening in the same order in the 3 cases

**Comment by trufae** [comment]
What's left to merge this?

**Comment by serpilliere** [comment]
Sorry for the delay @trufae, and thank you for your fix!

**Comment by trufae** [comment]
Thanks!

**Pull request merged**
