### PR TITLE
implement NOP for arm and fix ldrsb

### PR DESCRIPTION
**Pull request by hax0kartik**

### CODE REVIEW

**Comment by hax0kartik** [comment]
Pushed a commit which fixes issue #978

**Comment by serpilliere** [comment]
I double checked on IDA, the mnemonic seems to be disassembled as (arm little endian):
```
D0 00 D1 11                 LDRNESB         R0, [R1]
```
Maybe I missed something here

**Comment by hax0kartik** [comment]
Yup, that's what I mentioned in issue #978, and as you said moving this instr to `mnemo_condm0` fixed it

**Comment by serpilliere** [comment]
Erf.
I checked against IDA and it seems the instruction is not decoded as `ldrsbne` but as `ldrnesb` !
So the instruction must be moved into `cond_m2`, not into `cond_m0`
Sorry for this @hax0kartik 
May you update the PR?

**Comment by hax0kartik** [comment]
Here is the assembled `NOP` instruction. http://shell-storm.org/online/Online-Assembler-and-Disassembler/?inst=Nop&arch=arm#assembly
Double checked with IDA

**Comment by hax0kartik** [comment]
@serpilliere  Moving the instruction into cond_m2 seems to break it again
```
Traceback (most recent call last):
  File "test.py", line 61, in <module>
    sb.call(GetLastError, JpegStruct_S)
  File "/usr/lib/python2.7/site-packages/miasm2/analysis/sandbox.py", line 705, in call
    super(self.__class__, self).call(prepare_cb, addr, *args)
  File "/usr/lib/python2.7/site-packages/miasm2/analysis/sandbox.py", line 139, in call
    self.jitter.continue_run()
  File "/usr/lib/python2.7/site-packages/miasm2/jitter/jitload.py", line 387, in continue_run
    return self.run_iterator.next()
  File "/usr/lib/python2.7/site-packages/miasm2/jitter/jitload.py", line 358, in runiter_once
    self.pc = self.run_at(self.pc)
  File "/usr/lib/python2.7/site-packages/miasm2/jitter/jitload.py", line 315, in run_at
    set(self.breakpoints_handler.callbacks.keys())
  File "/usr/lib/python2.7/site-packages/miasm2/jitter/jitcore.py", line 176, in run_at
    cur_block = self.disasm_and_jit_block(offset, cpu.vmmngr)
  File "/usr/lib/python2.7/site-packages/miasm2/jitter/jitcore.py", line 153, in disasm_and_jit_block
    self.add_block(cur_block)
  File "/usr/lib/python2.7/site-packages/miasm2/jitter/jitcore_python.py", line 62, in add_block
    irblocks_list = codegen.block2assignblks(asmblock)
  File "/usr/lib/python2.7/site-packages/miasm2/arch/arm/jit.py", line 43, in block2assignblks
    assignblk_head, assignblks_extra = self.ir_arch.instr2ir(instr)
  File "/usr/lib/python2.7/site-packages/miasm2/ir/ir.py", line 741, in instr2ir
    ir_bloc_cur, extra_irblocks = self.get_ir(instr)
  File "/usr/lib/python2.7/site-packages/miasm2/arch/arm/sem.py", line 1696, in get_ir
    instr_ir, extra_ir = get_mnemo_expr(self, instr, *args)
  File "/usr/lib/python2.7/site-packages/miasm2/arch/arm/sem.py", line 1645, in get_mnemo_expr
    raise ValueError('unknown mnemo %s' % instr)
ValueError: unknown mnemo LDRSBNE    R0, [R0, 0x44]
```

**Comment by serpilliere** [comment]
Hi!

I will take the patch in its state.
The modification to fix the Miasm disassembler to have `ldrnesb` instead of `ldrsbne` is more complicated.

Moreover I see that a *lot* of mnemonics are in this case :sad:
So maybe we will do the big fix in a future PR
Are you ok with this @hax0kartik ?

**Comment by hax0kartik** [comment]
Yup

**Comment by serpilliere** [comment]
Thank you @hax0kartik !

**Pull request merged**
