### PR TITLE
parallel tests

### PR DESCRIPTION
**Pull request by stephengroat**
should improve test speed

### CODE REVIEW

**Comment by commial** [comment]
Well, it seems a good idea, but I'm afraid there might be a lot of redundancy. Does travails launch several instances for matrix?

**Comment by stephengroat** [comment]
yup, launches a bunch https://travis-ci.org/cea-sec/miasm/builds/478452513

don't know why travis didn't associate the build with this pr

**Comment by stephengroat** [comment]
@commial is the `tcc` code in `tests/test_all.py` still valid or should the references be removed?

**Comment by commial** [comment]
I don't see any TCC reference in test_all :/

**Comment by stephengroat** [comment]
@commial sorry about that, must have been looking at an old branch. cleaned it up

**Comment by serpilliere** [comment]
Thank @stephengroat !

**Comment by commial** [comment]
I'll take a closer look at how we can better dispatch tests (for now, I think example + regression already map 100% of the testset)

**Comment by stephengroat** [comment]
@commial great! if you could keep in mind still being able to split out the gcc tests, could probably get macos build and test working on #930

**Pull request merged**
