### PR TITLE
Refactor API arguments

### PR DESCRIPTION
**Pull request by p-l-**
This adds the possibility to call `.func_args_*()` methods with an arguments list instead of the arguments count as the parameter, and get a `collections.namedtuple`. It is still possible to use the arguments count.

The calls in `os_dep/win_api_x86_32.py` have been updated, and some bugs have been fixed there.

Thanks to @commial (kamoul0x) for your help & time.

### CODE REVIEW

**Comment by p-l-** [comment]
All tests OK.

**Comment by commial** [comment]
Could you `git rebase -i` to `fixup` the commit 6a142409aab9e58b537ac1966e76368860acbcd9 with commit af612cfe212bbd64705191d84d50ef24b595f67d and then `push --force` ?
It should clean up the commit tree :).

**Comment by p-l-** [comment]
@commial you're right! Done.

**Comment by serpilliere** [comment]
Cool: I wanted such a feature for functions argument for a while!

**Pull request merged**
