### PR TITLE
chore: add generated files to gitignore file

### PR DESCRIPTION
**Pull request by P403n1x87**
The test runs generate many files that should be ignored by git.

### CODE REVIEW

**Comment by mrexodia** [comment]
Any progress on this?

**Comment by P403n1x87** [comment]
This is just waiting for review I guess. @serpilliere apologies if I'm pinging the wrong person, but I don't seem to be able to assign reviewers to this, nor ask for a review.

**Comment by mrexodia** [comment]
On Windows it's also missing `*.pyd`

**Comment by serpilliere** [comment]
Thank you for the fix @P403n1x87  & @mrexodia !

**Pull request merged**
