### PR TITLE
Handle movupd bidirectional mode

### PR DESCRIPTION
**Pull request by nguigo**

### CODE REVIEW

**Comment by serpilliere** [comment]
Hi!
It seems you have inverted the arguments in both cases of the instruction.
Can you confirm this?

**Comment by nguigo** [comment]
Hi, sorry I accidentally submitted an old and erroneous commit. Should I just close this request and resubmit?

**Comment by serpilliere** [comment]
Ho!
Or you can erase your branch, so the commit will be updated!
(you can reopen this PR as I see you closed it)

**Comment by serpilliere** [comment]
Seems ok for me.
Thank you for the fix @nguigo !

**Comment by nguigo** [comment]
Happy to contribute. Miasm is really good stuff.

**Pull request merged**
