### PR TITLE
Fix Dockerfile (UnicodeEncodeError)

### PR DESCRIPTION
**Pull request by clslgrnc**
The python3 version that comes with stretch does not like accented characters, `docker build .` results in:
``` pytb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-oosab_wh-build/setup.py", line 344, in <module>
    buil_all()
  File "/tmp/pip-oosab_wh-build/setup.py", line 269, in buil_all
    url = "http://miasm.re",
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 272, in run
    writer(self, ep.name, os.path.join(self.egg_info, ep.name))
  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 600, in write_pkg_info
    metadata.write_pkg_info(cmd.egg_info)
  File "/usr/lib/python3.5/distutils/dist.py", line 1107, in write_pkg_info
    self.write_pkg_file(pkg_info)
  File "/tmp/pip-oosab_wh-build/setup.py", line 328, in _write_pkg_file
    _write_pkg_file_orig(self, tmpfd)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 56, in write_pkg_file
    file.write('Description: %s\n' % long_desc)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 24661: ordinal not in range(128)
```
`long_desc` is read from `README.md` in `setup.py`.

Updating the Dockerfile to use buster instead fixed the issue, but then I got carried away...
Feel free to cherry pick whatever you deem suitable.

### CODE REVIEW

**Comment by serpilliere** [comment]
Hi @clslgrnc 
First, thank you for the PR.
I have a question:
It seems that you add the `pinned_requirements.txt ` to the repository.
@fvanniere hinted me that it's a generated file, so here is the question:
Is it mandatory, or is there a reason you add it to the repository ?

Thank you again!

**Comment by clslgrnc** [comment]
Yes, `pinned_requirements.txt` is auto-generated.
I like having version controlled pinned requirements for Dockerfiles to improve the reproducibility of the build.

But since:

- miasm does not have a lot of dependencies
- z3-solver and llvmlite are already pinned
- CI regularly tests miasm with the non-pinned requirements

This is probably not necessary, and may even become a hassle since this file will have to be updated when requirements change (this can be automated but still).

Feel free to revert 810a8ad if you wish, I believe you have commit access to my branch. I can also do it myself if you prefer.

**Comment by serpilliere** [comment]
Hi @clslgrnc 
Maybe I have missed something but I didn't manage to only merge the first commits without the faulty commit.
Can you push again your branch without it ?

**Comment by clslgrnc** [comment]
done

**Comment by serpilliere** [comment]
Trugarez Colas!

**Pull request merged**
