### PR TITLE
TranslatorZ3: Handling 'parity' and '-' unary operators, and raising err...

### PR DESCRIPTION
**Pull request by fmonjalet**
...ors properly for other unhandled operators.

This should fix issue #127. It -might- conflict with PR #126 (not a big deal to merge though).

### CODE REVIEW

**Comment by fmonjalet** [comment]
Parity should be ok now.

**Comment by fmonjalet** [comment]
I also fixed ExprId to handle properly non-str expr.name (typically asm_label). When possible, asm_label are translated to BitVecVal (concrete value) rather than BitVec (symbolic value). Thanks @mrphrazer for the bug reports.

**Comment by mrphrazer** [comment]
Update regarding IRC:
I broke the problem down to the following:
```
int foo(int a)
{
   if (a % 122 == 1337) {do s.th.}
   else ....
}
```

Triggering {do s.th.} should be UNSAT, but the miasm z3 outputs a value.

Assembly:
```
  400546:       55                      push   %rbp
  400547:       48 89 e5                mov    %rsp,%rbp
  40054a:       89 7d fc                mov    %edi,-0x4(%rbp)
  40054d:       89 75 f8                mov    %esi,-0x8(%rbp)
  400550:       89 55 f4                mov    %edx,-0xc(%rbp)
  400553:       8b 4d fc                mov    -0x4(%rbp),%ecx
  400556:       ba 3f c5 25 43          mov    $0x4325c53f,%edx
  40055b:       89 c8                   mov    %ecx,%eax
  40055d:       f7 ea                   imul   %edx
  40055f:       c1 fa 05                sar    $0x5,%edx
  400562:       89 c8                   mov    %ecx,%eax
  400564:       c1 f8 1f                sar    $0x1f,%eax
  400567:       29 c2                   sub    %eax,%edx
  400569:       89 d0                   mov    %edx,%eax
  40056b:       6b c0 7a                imul   $0x7a,%eax,%eax
  40056e:       29 c1                   sub    %eax,%ecx
  400570:       89 c8                   mov    %ecx,%eax
  400572:       3d 39 05 00 00          cmp    $0x539,%eax
  400577:       75 07                   jne    400580 <foo+0x3a>
```

IR block:
```
loc_0000000000400546:0x00400546
	RSP = {(RSP[0:64]+(- 0x8)),0,64}
	@64[(RSP[0:64]+(- 0x8))] = RBP

	RBP = RSP

	@32[(RBP+0xFFFFFFFFFFFFFFFC)] = RDI[0:32]

	@32[(RBP+0xFFFFFFFFFFFFFFF8)] = RSI[0:32]

	@32[(RBP+0xFFFFFFFFFFFFFFF4)] = RDX[0:32]

	RCX = {@32[(RBP+0xFFFFFFFFFFFFFFFC)],0,32, 0x0,32,64}

	RDX = {0x4325C53F,0,32, 0x0,32,64}

	RAX = {RCX[0:32],0,32, 0x0,32,64}

	RAX = {({RAX[0:32],0,32, (RAX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64}*{RDX[0:32],0,32, (RDX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64})[0:32],0,32, 0x0,32,64}
	RDX = {({RAX[0:32],0,32, (RAX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64}*{RDX[0:32],0,32, (RDX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64})[32:64],0,32, 0x0,32,64}
	cf = ((({RAX[0:32],0,32, (RAX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64}*{RDX[0:32],0,32, (RDX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64})+(- {({RAX[0:32],0,32, (RAX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64}*{RDX[0:32],0,32, (RDX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64})[0:32],0,32, (({RAX[0:32],0,32, (RAX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64}*{RDX[0:32],0,32, (RDX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64})[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64}))?(0x1,0x0))
	of = ((({RAX[0:32],0,32, (RAX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64}*{RDX[0:32],0,32, (RDX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64})+(- {({RAX[0:32],0,32, (RAX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64}*{RDX[0:32],0,32, (RDX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64})[0:32],0,32, (({RAX[0:32],0,32, (RAX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64}*{RDX[0:32],0,32, (RDX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64})[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64}))?(0x1,0x0))

	cf = (RDX[0:32] a>> (0x5+(- 0x1)))[0:1]
	of = 0x0
	RDX = {(RDX[0:32] a>> 0x5),0,32, 0x0,32,64}
	zf = ((RDX[0:32] a>> 0x5)?(0x0,0x1))
	nf = (RDX[0:32] a>> 0x5)[31:32]
	pf = (parity ((RDX[0:32] a>> 0x5)&0xFF))

	RAX = {RCX[0:32],0,32, 0x0,32,64}

	cf = (RAX[0:32] a>> (0x1F+(- 0x1)))[0:1]
	of = 0x0
	RAX = {(RAX[0:32] a>> 0x1F),0,32, 0x0,32,64}
	zf = ((RAX[0:32] a>> 0x1F)?(0x0,0x1))
	nf = (RAX[0:32] a>> 0x1F)[31:32]
	pf = (parity ((RAX[0:32] a>> 0x1F)&0xFF))

	zf = ((RDX[0:32]+(- RAX[0:32]))?(0x0,0x1))
	nf = (RDX[0:32]+(- RAX[0:32]))[31:32]
	pf = (parity ((RDX[0:32]+(- RAX[0:32]))&0xFF))
	af = (((RDX[0:32]+(- RAX[0:32]))&0x10)?(0x1,0x0))
	cf = (((RDX[0:32]^RAX[0:32])^(RDX[0:32]+(- RAX[0:32])))^((RDX[0:32]^(RDX[0:32]+(- RAX[0:32])))&(RDX[0:32]^RAX[0:32])))[31:32]
	of = ((RDX[0:32]^(RDX[0:32]+(- RAX[0:32])))&(RDX[0:32]^RAX[0:32]))[31:32]
	RDX = {(RDX[0:32]+(- RAX[0:32])),0,32, 0x0,32,64}

	RAX = {RDX[0:32],0,32, 0x0,32,64}

	RAX = {({RAX[0:32],0,32, (RAX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64}*{0x7A,0,32, (0x7A[31:32]?(0xFFFFFFFF,0x0)),32,64})[0:32],0,32, 0x0,32,64}
	cf = ((({RAX[0:32],0,32, (RAX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64}*{0x7A,0,32, (0x7A[31:32]?(0xFFFFFFFF,0x0)),32,64})+(- {({RAX[0:32],0,32, (RAX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64}*{0x7A,0,32, (0x7A[31:32]?(0xFFFFFFFF,0x0)),32,64})[0:32],0,32, (({RAX[0:32],0,32, (RAX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64}*{0x7A,0,32, (0x7A[31:32]?(0xFFFFFFFF,0x0)),32,64})[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64}))?(0x1,0x0))
	of = ((({RAX[0:32],0,32, (RAX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64}*{0x7A,0,32, (0x7A[31:32]?(0xFFFFFFFF,0x0)),32,64})+(- {({RAX[0:32],0,32, (RAX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64}*{0x7A,0,32, (0x7A[31:32]?(0xFFFFFFFF,0x0)),32,64})[0:32],0,32, (({RAX[0:32],0,32, (RAX[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64}*{0x7A,0,32, (0x7A[31:32]?(0xFFFFFFFF,0x0)),32,64})[0:32][31:32]?(0xFFFFFFFF,0x0)),32,64}))?(0x1,0x0))

	zf = ((RCX[0:32]+(- RAX[0:32]))?(0x0,0x1))
	nf = (RCX[0:32]+(- RAX[0:32]))[31:32]
	pf = (parity ((RCX[0:32]+(- RAX[0:32]))&0xFF))
	af = (((RCX[0:32]+(- RAX[0:32]))&0x10)?(0x1,0x0))
	cf = (((RCX[0:32]^RAX[0:32])^(RCX[0:32]+(- RAX[0:32])))^((RCX[0:32]^(RCX[0:32]+(- RAX[0:32])))&(RCX[0:32]^RAX[0:32])))[31:32]
	of = ((RCX[0:32]^(RCX[0:32]+(- RAX[0:32])))&(RCX[0:32]^RAX[0:32]))[31:32]
	RCX = {(RCX[0:32]+(- RAX[0:32])),0,32, 0x0,32,64}

	RAX = {RCX[0:32],0,32, 0x0,32,64}

	zf = ((RAX[0:32]+(- 0x539))?(0x0,0x1))
	nf = (RAX[0:32]+(- 0x539))[31:32]
	pf = (parity ((RAX[0:32]+(- 0x539))&0xFF))
	cf = (((RAX[0:32]^0x539)^(RAX[0:32]+(- 0x539)))^((RAX[0:32]^(RAX[0:32]+(- 0x539)))&(RAX[0:32]^0x539)))[31:32]
	of = ((RAX[0:32]^(RAX[0:32]+(- 0x539)))&(RAX[0:32]^0x539))[31:32]
	af = (((RAX[0:32]+(- 0x539))&0x10)?(0x1,0x0))

	RIP = (zf?(loc_0000000000400579:0x00400579,loc_0000000000400580:0x00400580))
	IRDst = (zf?(loc_0000000000400579:0x00400579,loc_0000000000400580:0x00400580))
```

Symbolic execution on IR:
```
(((RDI_init[0:32] a>> 0x1F)*0x7A)+RDI_init[0:32]+0xFFFFFAC7)
```
Lastly, the resulting z3 expression:
```
(Extract(31, 0, RDI_init) >> 31)*122 +
Extract(31, 0, RDI_init) +
4294965959```
```
z3 outputs then 
```
[RDI_init = 1337]
```

**Comment by serpilliere** [comment]
Hi

Ok, there is a bug in the following simplification:
```
    # (a * int)[0:y] => (a[0:y] * int[0:y])
    elif (isinstance(e.arg, ExprOp) and
        e.arg.op == "*" and
        isinstance(e.arg.args[-1], ExprInt)):
        args = [e_s.expr_simp_wrapper(a[e.start:e.stop]) for a in e.arg.args]
        e = ExprOp(e.arg.op, *args)
```

The comment is correct, but the code doesn't do what's in the comment. The code which checks the slice begins with a 0 (in the [0:y]) is not present. Shame on me.

The output seems more interesting:
```
zf = (((- (((- (RDI_init[0:32] a>> 0x1F))+((({RDI_init[0:32],0,32, (RDI_init[31:32]?(0xFFFFFFFF,0x0)),32,64}*0x4325C53F) >> 0x20)[0:32] a>> 0x5))*0x7A))+RDI_init[0:32]+0xFFFFFAC7)?(0x0,0x1))
```

The PR #129 fixes this bug
Is it ok for you?

**Comment by fmonjalet** [comment]
Hi,

Translation between 
```
(((RDI_init[0:32] a>> 0x1F)*0x7A)+RDI_init[0:32]+0xFFFFFAC7)
```
and
```
(Extract(31, 0, RDI_init) >> 31)*122 + Extract(31, 0, RDI_init) + 4294965959
```

Seems correct to me (tell me if I missed something). Would it be possible to have the equation you give Z3 to solve? This expression has no constraints, so any `RDI_init` satisfies it.
Also, I do not get how the modulus is translated to asm here...

**Comment by mrphrazer** [comment]
for me it works fine now, thx! :)

**Pull request merged**
