### PR TITLE
Dg has loop

### PR DESCRIPTION
**Pull request by serpilliere**
Add loop detection algorithm to the graph class.
Update `DependencyResult` to use this algorithm.

Thanks to @carolineLe for the loop detection algorithm

### CODE REVIEW

**Comment by mrphrazer** [comment]
just a quick reminer, if necessary, I will add more details later. The DiGraph class already has to loop algorithms for loop detection: `compute_natural loops` and `compute_strongly_connected_component`. the second one finds all loops in a graph: every strongly connected component with more than one node is a loop. however, this will not detect self-loops. but, a self-loop is a natural loop. therefore, all loops in the graph can be detected by combining the two algorithms. 

If needed, I will add more details tomorrow.

**Comment by commial** [comment]
The goal of `has_loop` is to stop and return if at least one cycle has been detected, without any information on that loop.

Correct me if I'm wrong, but a DFS seems to be the fastest way to obtain such a result, without involving complex algorithm such as `compute_strongly_connected_components` and natural loop detection.
By the way, I think that a quicker solution for self loops hunting is a linear traversal of `graph._nodes_succ` looking for a value which is a set of only the key.

**Comment by mrphrazer** [comment]
Hi, I was not sure if that approach would also detect irreducible loops. I had some time for re-thinking;  you are right, this approach will detect both kind of loops. 

Thanks for that :)

**Comment by serpilliere** [comment]
Ok.

So do you agree with us to merge the PR?
It's clear, we could design an algorithm built on top of `compute_strongly_connected_components` to detect all loops, but what do you think of keeping this current `has_loop` for this usecase, *and* keeping `compute_strongly_connected_components` for, let say, advanced future needs?  :wink:

**Comment by mrphrazer** [comment]
Sure! I first wasn't sure about the soundness (irreducible loops). For this use case, it is faster than my approach mentioned above.  Thanks for asking :)

In addition, you are right. Both should stay inside since they have different use cases. For instance, strongly connected components yields outermost loops, which is useful for loop unrolling.

**Pull request merged**
