### PR TITLE
win_api_x86_32: add further common windows API functions

### PR DESCRIPTION
**Pull request by williballenthin**
Found these while trying to get a naive "Hello world" VS2017 binary emulating under miasm. (doesn't yet work due to string table/MBS initialization. Not yet sure if I'll chase that down.)

### CODE REVIEW

**Comment by serpilliere** [comment]
Hi @williballenthin , thank you for PR!
It's seems you are on your way to rewrite a complete windows in Python :smile: 

Just a few remarks: In `win_api_x86_32` there is a special object called the ` c_winobjs` (https://github.com/cea-sec/miasm/blob/master/miasm/os_dep/win_api_x86_32.py#L133)
This object represents the current "windows environment":  it stores various stuffs from registry keys to system date. This object is instantiated once (https://github.com/cea-sec/miasm/blob/master/miasm/os_dep/win_api_x86_32.py#L133) and APIs which needs one of those variables use the global variable `winobj`. This is a convenient way for a Miasm user to customize, let say a keyboard layout or the current date:
```python
from miasm.os_dep.win_api_x86_32 import winobjs
winobjs.hkey_handles.update({
    0x80000000: "hkey_classes_root",
...
})
```

As I can see, you have integrated some environment dependent variables in your APIs. Maybe It can be interesting to move them in it. 

Anyway, as you did the big part of the job, tell me if you want to give it a try or if you prefer I merge the PR like this (and we will patch this later) !

**Comment by serpilliere** [comment]
Another remark:
In most cases, when we run "classic" windows binaries, we don't start at the entry point, but rather in the `winmain`: this avoid a lot of hard work (you did) like stack cookie initialisation. But this has some drawbacks: the heap pointer is not initialized and stuffs like that, so it has to be fixed 'manually'.

**Comment by serpilliere** [comment]
I am merging the code like this: I will fix it in another PR

**Comment by williballenthin** [comment]
Hopefully I'll get a chance to make the fixes before you do; though, it will be when my attention returns at work in a week or two.

**Comment by williballenthin** [comment]
anyways, thanks for merging!

**Pull request merged**
