### PR TITLE
Passes simplifier

### PR DESCRIPTION
**Pull request by serpilliere**
Include idea and modifications described in #954

### CODE REVIEW

**Comment by KosBeg** [comment]
tested this PR with movfuscated binary industries, that I upload in PR #955
in some cases it works as expected

memory propagation 1
-------------------
from master
```
@32[0x81FD140] = 0x88051C51
@32[@32[@32[0x83FD198] * 0x4 + 0x83FD1A0]] = @32[0x81FD140]
```
from this pr
```
@32[0x81FD140] = 0x88051C51
@32[@32[@32[0x83FD198] * 0x4 + 0x83FD1A0]] = 0x88051C51
```
memory propagation 2
-------------------------
```
@32[0x81FD034] = 0x8804857E
EDX.38 = {@8[@32[{@8[0x81FD030] 0 8, 0x0 8 32} * 0x4 + 0x8057640] + {@8[0x81FD034] 0 8, 0x0 8 32}] 0 8, 0x0 8 32}
@32[0x81FD020] = {@8[@32[{@8[0x81FD030] 0 8, 0x0 8 32} * 0x4 + 0x8057640] + {@8[0x81FD034] 0 8, 0x0 8 32}] 0 8, 0x0 8 32}
```
```
@32[0x81FD034] = 0x8804857E
EDX.38 = {@8[@32[{@8[0x81FD030] 0 8, 0x0 8 32} * 0x4 + 0x8057640] + 0x7E] 0 8, 0x0 8 32}
@32[0x81FD020] = {@8[@32[{@8[0x81FD030] 0 8, 0x0 8 32} * 0x4 + 0x8057640] + 0x7E] 0 8, 0x0 8 32}
```
-------------------

but in some cases it works in a strange way:
master
```
@32[0x81FD02C] = {@8[@32[{@8[0x81FD033] 0 8, EAX.36[8:32] 8 32} * 0x4 + 0x8057640] + {@8[0x81FD037] 0 8, EDX.42[8:32] 8 32}] 0 8, EDX.42[8:32] 8 32}
@32[0x81FD020] = @32[@32[@32[0x81FD020] * 0x4 + 0x80540E0] + @32[0x81FD024] * 0x4]
@32[0x81FD020] = @32[@32[@32[0x81FD020] * 0x4 + 0x80540E0] + @32[0x81FD028] * 0x4]
@32[0x81FD020] = @32[@32[@32[0x81FD020] * 0x4 + 0x80540E0] + @32[0x81FD02C] * 0x4]
ECX.10 = @32[0x81FD020]
@32[0x83FD1B4] = 0x8054090
@32[@32[ECX.10 * 0x4 + 0x83FD1B0]] = @32[0x85FD1D0]
@32[0x83FD1B4] = 0x8054094
@32[@32[ECX.10 * 0x4 + 0x83FD1B0]] = @32[0x85FD1D4]
@32[0x83FD1B4] = 0x8054098
@32[@32[ECX.10 * 0x4 + 0x83FD1B0]] = @32[0x85FD1D8]
@32[0x83FD1B4] = 0x805409C
@32[@32[ECX.10 * 0x4 + 0x83FD1B0]] = @32[0x85FD1DC]
@32[0x83FD1B4] = 0x80540A0
@32[@32[ECX.10 * 0x4 + 0x83FD1B0]] = @32[0x85FD1E0]
@32[0x83FD1B4] = 0x80540A4
@32[@32[ECX.10 * 0x4 + 0x83FD1B0]] = @32[0x85FD1E4]
@32[0x83FD1B4] = 0x80540B0
EAX.54 = @32[ECX.10 * 0x4 + 0x83FD1B0]
@32[@32[ECX.10 * 0x4 + 0x83FD1B0]] = @32[0x85FD1E8]
@32[EAX.54 + 0x4] = @32[0x85FD1EC]
@32[0x83FD1B4] = 0x80540B8
EAX.55 = @32[ECX.10 * 0x4 + 0x83FD1B0]
@32[@32[ECX.10 * 0x4 + 0x83FD1B0]] = @32[0x85FD1F0]
@32[EAX.55 + 0x4] = @32[0x85FD1F4]
```
PR
```
@32[0x81FD02C] = {@8[@32[{@8[0x81FD033] 0 8, EAX.36[8:32] 8 32} * 0x4 + 0x8057640] + {@8[0x81FD037] 0 8, EDX.42[8:32] 8 32}] 0 8, EDX.42[8:32] 8 32}
EAX.40 = @32[@32[@32[0x81FD020] * 0x4 + 0x80540E0] + @32[0x81FD024] * 0x4]
@32[0x81FD020] = @32[@32[@32[0x81FD020] * 0x4 + 0x80540E0] + @32[0x81FD024] * 0x4]
EAX.43 = @32[@32[EAX.40 * 0x4 + 0x80540E0] + @32[0x81FD028] * 0x4]
@32[0x81FD020] = @32[@32[EAX.40 * 0x4 + 0x80540E0] + @32[0x81FD028] * 0x4]
EAX.46 = @32[@32[EAX.43 * 0x4 + 0x80540E0] + @32[0x81FD02C] * 0x4]
@32[0x81FD020] = @32[@32[EAX.43 * 0x4 + 0x80540E0] + @32[0x81FD02C] * 0x4]
@32[0x81FD020] = EAX.46
@32[0x83FD1B4] = 0x8054090
@32[@32[EAX.46 * 0x4 + 0x83FD1B0]] = @32[0x85FD1D0]
@32[0x83FD1B4] = 0x8054094
@32[@32[EAX.46 * 0x4 + 0x83FD1B0]] = @32[0x85FD1D4]
@32[0x83FD1B4] = 0x8054098
@32[@32[EAX.46 * 0x4 + 0x83FD1B0]] = @32[0x85FD1D8]
@32[0x83FD1B4] = 0x805409C
@32[@32[EAX.46 * 0x4 + 0x83FD1B0]] = @32[0x85FD1DC]
@32[0x83FD1B4] = 0x80540A0
@32[@32[EAX.46 * 0x4 + 0x83FD1B0]] = @32[0x85FD1E0]
@32[0x83FD1B4] = 0x80540A4
@32[@32[EAX.46 * 0x4 + 0x83FD1B0]] = @32[0x85FD1E4]
@32[0x83FD1B4] = 0x80540B0
EAX.54 = @32[EAX.46 * 0x4 + 0x83FD1B0]
@32[@32[EAX.46 * 0x4 + 0x83FD1B0]] = @32[0x85FD1E8]
@32[EAX.54 + 0x4] = @32[0x85FD1EC]
@32[0x83FD1B4] = 0x80540B8
EAX.55 = @32[EAX.46 * 0x4 + 0x83FD1B0]
@32[@32[EAX.46 * 0x4 + 0x83FD1B0]] = @32[0x85FD1F0]
@32[EAX.55 + 0x4] = @32[0x85FD1F4]
```
but after manual const and expr propagation we will have same results in both cases:
```
@32[0x81FD02C] = {@8[@32[{@8[0x81FD033] 0 8, EAX.36[8:32] 8 32} * 0x4 + 0x8057640] + {@8[0x81FD037] 0 8, EDX.42[8:32] 8 32}] 0 8, EDX.42[8:32] 8 32}
@32[0x83FD1B4] = 0x8054090
@32[@32[@32[@32[@32[@32[@32[@32[@32[0x81FD020] * 0x4 + 0x80540E0] + @32[0x81FD024] * 0x4] * 0x4 + 0x80540E0] + @32[0x81FD028] * 0x4] * 0x4 + 0x80540E0] + @32[0x81FD02C] * 0x4] * 0x4 + 0x83FD1B0]] = @32[0x85FD1D0]
@32[0x83FD1B4] = 0x8054094
@32[@32[@32[@32[@32[@32[@32[@32[@32[0x81FD020] * 0x4 + 0x80540E0] + @32[0x81FD024] * 0x4] * 0x4 + 0x80540E0] + @32[0x81FD028] * 0x4] * 0x4 + 0x80540E0] + @32[0x81FD02C] * 0x4] * 0x4 + 0x83FD1B0]] = @32[0x85FD1D4]
@32[0x83FD1B4] = 0x8054098
@32[@32[@32[@32[@32[@32[@32[@32[@32[0x81FD020] * 0x4 + 0x80540E0] + @32[0x81FD024] * 0x4] * 0x4 + 0x80540E0] + @32[0x81FD028] * 0x4] * 0x4 + 0x80540E0] + @32[0x81FD02C] * 0x4] * 0x4 + 0x83FD1B0]] = @32[0x85FD1D8]
@32[0x83FD1B4] = 0x805409C
@32[@32[@32[@32[@32[@32[@32[@32[@32[0x81FD020] * 0x4 + 0x80540E0] + @32[0x81FD024] * 0x4] * 0x4 + 0x80540E0] + @32[0x81FD028] * 0x4] * 0x4 + 0x80540E0] + @32[0x81FD02C] * 0x4] * 0x4 + 0x83FD1B0]] = @32[0x85FD1DC]
@32[0x83FD1B4] = 0x80540A0
@32[@32[@32[@32[@32[@32[@32[@32[@32[0x81FD020] * 0x4 + 0x80540E0] + @32[0x81FD024] * 0x4] * 0x4 + 0x80540E0] + @32[0x81FD028] * 0x4] * 0x4 + 0x80540E0] + @32[0x81FD02C] * 0x4] * 0x4 + 0x83FD1B0]] = @32[0x85FD1E0]
@32[0x83FD1B4] = 0x80540A4
@32[@32[@32[@32[@32[@32[@32[@32[@32[0x81FD020] * 0x4 + 0x80540E0] + @32[0x81FD024] * 0x4] * 0x4 + 0x80540E0] + @32[0x81FD028] * 0x4] * 0x4 + 0x80540E0] + @32[0x81FD02C] * 0x4] * 0x4 + 0x83FD1B0]] = @32[0x85FD1E4]
@32[0x83FD1B4] = 0x80540B0
@32[@32[@32[@32[@32[@32[@32[@32[@32[0x81FD020] * 0x4 + 0x80540E0] + @32[0x81FD024] * 0x4] * 0x4 + 0x80540E0] + @32[0x81FD028] * 0x4] * 0x4 + 0x80540E0] + @32[0x81FD02C] * 0x4] * 0x4 + 0x83FD1B0]] = @32[0x85FD1E8]
@32[@32[@32[@32[@32[@32[@32[@32[@32[0x81FD020] * 0x4 + 0x80540E0] + @32[0x81FD024] * 0x4] * 0x4 + 0x80540E0] + @32[0x81FD028] * 0x4] * 0x4 + 0x80540E0] + @32[0x81FD02C] * 0x4] * 0x4 + 0x83FD1B0] + 0x4] = @32[0x85FD1EC]
@32[0x83FD1B4] = 0x80540B8
@32[@32[@32[@32[@32[@32[@32[@32[@32[0x81FD020] * 0x4 + 0x80540E0] + @32[0x81FD024] * 0x4] * 0x4 + 0x80540E0] + @32[0x81FD028] * 0x4] * 0x4 + 0x80540E0] + @32[0x81FD02C] * 0x4] * 0x4 + 0x83FD1B0]] = @32[0x85FD1F0]
@32[@32[@32[@32[@32[@32[@32[@32[@32[0x81FD020] * 0x4 + 0x80540E0] + @32[0x81FD024] * 0x4] * 0x4 + 0x80540E0] + @32[0x81FD028] * 0x4] * 0x4 + 0x80540E0] + @32[0x81FD02C] * 0x4] * 0x4 + 0x83FD1B0] + 0x4] = @32[0x85FD1F4]
```
------------------
so in general everything is correct, but it just looks weird
and there are many such unpropagated registers-variables in SSA form

and you can also meet such oddities:
master
```
@32[0x805409C] = @32[0x8054090] ; just one line
```
pr
```
EAX.1902 = @32[0x8054090]
@32[0x805409C] = @32[0x8054090]
@32[0x805409C] = EAX.1902
```
that obviously it can be simplified to:
```
@32[0x805409C] = @32[0x8054090]
@32[0x805409C] = @32[0x8054090]
```
and then to(what is the same with master):
```
@32[0x805409C] = @32[0x8054090]
```
but with this PR this didn't happen

**Comment by serpilliere** [comment]
Hi @KosBeg !
Thank you for the feed back!
Question: have you got the initial IR of:
```
@32[0x805409C] = @32[0x8054090] ; just one line
```

Because in the simplified version from the PR, it seems the memory value pass through EAX.
So this means (maybe I am wrong) that EAX was used in the original IR.
So I don't see why the master "allowed" itself to propagate the value.
That's a strange point, or we had a problem in master :smiley:

**Comment by commial** [comment]
Well, I'm not so sure about at least the second part of your comment.
```
EAX.1902 = @32[0x8054090]
@32[0x805409C] = @32[0x8054090]
@32[0x805409C] = EAX.1902
```
First, we could say that the first write is dead, so it can be removed. But actually, on some architecture / SoC, writing to a specific address does have side effects (talking to external components, etc.). So we can't safely remove it in the general case.

Regarding the replacement of EAX, we may indeed be able to propagate it, as we know there isn't memory aliases (addresses are fully resolved).
But again (and I don't known if it is something we want to avoid), if `@32[0x8054090]` is a read from an external component (and `@32[0x805409C]` a write), we are replacing:
```
temp = read1
write(read2)
write(temp)
```
By:
```
write(read1)
write(read2)
```
Which obviously invert the data written.

**Comment by KosBeg** [comment]
> Question: have you got the initial IR of:

from `graph_irflow_raw.dot`
```
EAX = @32[0x8054090]
@32[0x805409C] = EAX
EAX = @32[0x805409C]
@32[0x805409C] = EAX
```
from `final.dot` from `master`
```
@32[0x805409C] = @32[0x8054090] ; just one line
```
from `final.dot` from this PR
```
EAX.1902 = @32[0x8054090]
@32[0x805409C] = @32[0x8054090]
@32[0x805409C] = EAX.1902
```

so it seems
> we had a problem in master 😃
----------------
> But actually, on some architecture / SoC, writing to a specific address does have side effects (talking to external components, etc.). So we can't safely remove it in the general case.

Yeah, my bad.
I am not very familiar with other architectures.

**Pull request merged**
